### PR TITLE
Add series information to badge page

### PR DESCRIPTION
**Pull request by lubomir**
Add a box to the badge detail page that shows all badges in the same
series. The relationship is stored in the database. Current badge is
highlighted with blue-tinted background.

### CODE REVIEW

**Comment by bowlofeggs** [comment]
LGTM!

**Comment by bowlofeggs** [comment]
In https://github.com/fedora-infra/tahrir-api/issues/37 it sounded like maybe we won't be doing this change any more. @lubomir and @pypingou, how do you want to proceed with this pull request?

**Comment by sayanchowdhury** [comment]
@bowlofeggs I think we can close this PR but let me work on my PR tomorrow and handle all PRs related to Badges Series accordingly.

**Comment by sayanchowdhury** [comment]
A badge page can be part of multiple Series.  We need to think about the design on how to show multiple Series. Closing this PR.

**Pull request closed without merging**
